# Change these first
owner: byemc # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: "Bye's Site"
    url: https://www.byemc.xyz
  - name: ByeMC Static
    url: https://static.byemc.xyz
  - name: ByeCorps
    url: https://byecorps.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: www.byemc.xyz
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Bye's site status**"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
