# Change these first
owner: byemc # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: byemc

sites:
  - name: "Bye's Site"
    url: https://www.byemc.xyz
  - name: ByeCorps
    url: https://byecorps.com
  - name: ByeCasts
    url: https://byecasts.com
  - name: ByeBot (discord)
    url: http://bbapi.byemc.xyz/info

assignees:
  - byemc
  
status-website:
  theme: default
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status2.byemc.xyz
  #baseUrl: /status
  name: "ByeMC's Status"
  navbar:
    - title: Status
      href: /
    - title: Backup Status
      href: https://bye.betteruptime.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: byemc.xyz
      href: https://byemc.xyz/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
